/**
 * Agent Types - OpenAI tool-calling based agent
 * 
 * The agent can:
 * 1. Interpret user intent
 * 2. Call tools (actions) autonomously
 * 3. Chain multiple operations
 * 4. Handle clarifications
 */

import type { AreaNode, Group, Proposal } from '@/types';
import type { ExpandDetailLevel } from '../formulaService';

// ============================================
// OPENAI TOOL CALLING TYPES
// ============================================

/**
 * OpenAI tool definition schema
 */
export interface ToolDefinition {
  type: 'function';
  function: {
    name: string;
    description: string;
    parameters: {
      type: 'object';
      properties: Record<string, ToolParameter>;
      required: string[];
    };
  };
}

export interface ToolParameter {
  type: 'string' | 'number' | 'boolean' | 'array' | 'object';
  description: string;
  enum?: string[];
  items?: { type: string };
}

/**
 * Tool call from OpenAI response
 */
export interface ToolCall {
  id: string;
  type: 'function';
  function: {
    name: string;
    arguments: string; // JSON string
  };
}

/**
 * Result of executing a tool
 */
export interface ToolResult {
  toolCallId: string;
  success: boolean;
  result?: unknown;
  error?: string;
  /** Proposals generated by this tool */
  proposals?: Proposal[];
  /** Human-readable message */
  message?: string;
}

// ============================================
// AGENT CONTEXT & STATE
// ============================================

export interface AgentContext {
  /** All nodes in project */
  nodes: Record<string, AreaNode>;
  /** All groups in project */
  groups: Record<string, Group>;
  /** Currently selected node IDs */
  selectedNodeIds: string[];
  /** Currently selected group IDs */
  selectedGroupIds: string[];
  /** Detail level preference */
  detailLevel: ExpandDetailLevel;
  /** Project context/notes */
  projectContext?: string;
}

export interface AgentMessage {
  role: 'system' | 'user' | 'assistant' | 'tool';
  content: string | null;
  tool_calls?: ToolCall[];
  tool_call_id?: string;
}

export interface AgentState {
  /** Conversation messages */
  messages: AgentMessage[];
  /** Accumulated proposals from tool calls */
  proposals: Proposal[];
  /** Current iteration (for loop detection) */
  iteration: number;
  /** Max iterations before stopping */
  maxIterations: number;
  /** Whether agent has finished */
  done: boolean;
  /** Final response message */
  finalMessage?: string;
}

// ============================================
// AGENT RESPONSE
// ============================================

export interface AgentResponse {
  /** Final message to user */
  message: string;
  /** All proposals generated */
  proposals: Proposal[];
  /** Tool calls made (for transparency) */
  toolCalls: Array<{
    tool: string;
    args: Record<string, unknown>;
    result: string;
  }>;
  /** Number of iterations taken */
  iterations: number;
  /** Any warnings */
  warnings?: string[];
}
